<?php

namespace Container2a8BWtf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9vnLefrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9vnLefr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9vnLefr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jwtAuth' => ['privates', 'App\\Service\\JwtAuth', 'getJwtAuthService', true],
        ], [
            'jwtAuth' => 'App\\Service\\JwtAuth',
        ]);
    }
}
