<?php

namespace Container2a8BWtf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6e_BMy5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6e.BMy5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6e.BMy5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminUserController::login' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\OrderController::completeOrder' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\OrderController::createOrder' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\OrderController::readOrder' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\ProductController::createProduct' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\ProductController::deleteProduct' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\ProductController::readProduct' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminUserController:login' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\OrderController:completeOrder' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\OrderController:createOrder' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\OrderController:readOrder' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\ProductController:createProduct' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\ProductController:deleteProduct' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'App\\Controller\\ProductController:readProduct' => ['privates', '.service_locator.9vnLefr', 'get_ServiceLocator_9vnLefrService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminUserController::login' => '?',
            'App\\Controller\\OrderController::completeOrder' => '?',
            'App\\Controller\\OrderController::createOrder' => '?',
            'App\\Controller\\OrderController::readOrder' => '?',
            'App\\Controller\\ProductController::createProduct' => '?',
            'App\\Controller\\ProductController::deleteProduct' => '?',
            'App\\Controller\\ProductController::readProduct' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminUserController:login' => '?',
            'App\\Controller\\OrderController:completeOrder' => '?',
            'App\\Controller\\OrderController:createOrder' => '?',
            'App\\Controller\\OrderController:readOrder' => '?',
            'App\\Controller\\ProductController:createProduct' => '?',
            'App\\Controller\\ProductController:deleteProduct' => '?',
            'App\\Controller\\ProductController:readProduct' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
