<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2a8BWtf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2a8BWtf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2a8BWtf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2a8BWtf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2a8BWtf\App_KernelDevDebugContainer([
    'container.build_hash' => '2a8BWtf',
    'container.build_id' => '97f075af',
    'container.build_time' => 1623627103,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2a8BWtf');
